name: Lint

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  lint-ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pipenv"
      - name: Install pipenv
        run: |
          pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: pipenv sync --dev

      - name: Lint
        run: pipenv run lint-ci
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pipenv"

      - name: Install pipenv
        run: |
          pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: pipenv sync --dev

      - name: Type Lint
        run: pipenv run typelint
  pyright-build-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pipenv
        run: |
          pip install --upgrade pip
          pip install pipenv

      - name: Generate requirements.txt
        run: pipenv requirements --dev > requirements.txt

      - name: Upload requirements.txt
        uses: actions/upload-artifact@v4
        with:
          name: requirements.txt
          path: requirements.txt
  pyright:
    runs-on: ubuntu-latest
    needs:
      - "pyright-build-deps"
    strategy:
      matrix:
        pylance-version:
          - "latest-release"
          - "latest-prerelease"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: requirements.txt

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run pyright
        uses: jakebailey/pyright-action@v2
        with:
          pylance-version: ${{ matrix.pylance-version }}
          warnings: true
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install
        run: npm ci --dev

      - name: Check
        run: npm run mdlint:check
