name: Lint

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  lint-ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Sync dependencies
        run: uv sync --group lint

      - name: Lint
        run: uv run poe lint-ci
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Sync dependencies
        run: uv sync --group lint --group types

      - name: Type Lint
        run: uv run poe mypy
  ty:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Sync dependencies
        run: uv sync --group lint --group types

      - name: Type Lint
        run: uv run poe ty --output-format=github
  pyright:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pylance-version:
          - "latest-release"
          - "latest-prerelease"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Sync dependencies
        run: uv sync --group lint --group types

      - name: Add to path
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Run pyright
        uses: jakebailey/pyright-action@v3
        with:
          pylance-version: ${{ matrix.pylance-version }}
          warnings: true
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"

      - name: Install
        run: npm ci --dev

      - name: Check
        run: npm run mdlint:check
